{% set version = "4.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggthemes
  version: {{ version|replace("-", "_") }}

source:
  fn: ggthemes_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggthemes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggthemes/ggthemes_{{ version }}.tar.gz
  sha256: a2028b38eaed282655c46a1887873597975eddb75c3fca2ca2cac4be8c9e5024

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-purrr
    - r-scales
    - r-stringr
    - r-tibble
  run:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-purrr
    - r-scales
    - r-stringr
    - r-tibble

test:
  commands:
    - $R -e "library('ggthemes')"           # [not win]
    - "\"%R%\" -e \"library('ggthemes')\""  # [win]

about:
  home: http://github.com/jrnold/ggthemes
  license: GPL-2
  summary: Some extra themes, geoms, and scales for 'ggplot2'. Provides 'ggplot2' themes and
    scales that replicate the look of plots by Edward Tufte, Stephen Few, 'Fivethirtyeight',
    'The Economist', 'Stata', 'Excel', and 'The Wall Street Journal', among others.
    Provides 'geoms' for Tufte's box plot and range frame.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
