travis:
  secure:
    BINSTAR_TOKEN: r9hV1FN/behlUbZRK6vxooyKxvvi83Mjx6117MoedMT8Lo+jbNqeJn0dBcXbfw0BH2NjSF16KSlUcORrP6k/L4BbP9Neqe2S1H/NQE7Zwm95Tjj0ydL+Q9Vz7FzFNo5Reomc+rtyvReun+lJMxDrjSjBZAFKDgD4c6Zxz//KZiSY6uH2wauTl395fkjD10MIv7/N5vwbvdAfER8wJw3EWoIDsRcOmIUgSqrojzjJSgo5ADM4Gc1AAlJurX8xmlWJfc4Cp9kzF527zGvXWCsaVnL53VTQbpxHWzalWrx5I0iLWxy4DX/dDT+Hi1fYuyKnghcEyEzVzAvALZl2ZHntn5LXhK/qzZ8Yy+kWu4Jg84H20JAQhO9XXm40hjE7lXGwBJqfhxM5TNlBPAQ59WKM8mfC0P9hC9oMjNHeNa1cGHDrXcGdkmAIkcckkYSUDmr4IBxgHaQLuOROUleeT8uaVbYCj4yOzIE1F1kPiNT406FJ2z/ctowchh+m3usVBnKFZfi4WYmHP+Y2RJ9R79TkjlQISY37uCN2SDeRZvz5wCudkD4u0G1eyT9x/BjPcV8OCR5xuq1OpQZQR21V4EEoOHZjMRDIzQ4/CsMZrBhOnKn5DzRkKN2UDISdpQub3GQ5EIGBKVfh99d1ORrrmdVyonivlYti6PZ3+fjczQRu9eE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
