appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: JYI/fTfbzncqk8DMvglvS6Kt8i/lMym9D//5p+qE+q71VUl2zWfiezUVPx5uKHEg2XYl6ZIiUEgs+KJR/hQRm6qgpUxKEV53q6x8PBIy/KyIHYIFqGyB+O7L6CCl7HlkSrUYcVpEq5lfx1nFF1WFsJsWd+BT+ilT2ICuY6jKpazY0KR0Gm8wIy1Uhl90fzptZWProRS14o26E1TW78sSThE73xwbvrLsBeu+H171SE8lEbLEG0dK9rDd0yffdxtTNvLfEH9o3XYCLsV6BSVWlQzC+EfeGyfTd/7Z+3TMC2jEoNq0jumGjnsbsZWsfzayFAYx4wt3bN554quax34rVse9rOQ/UbJxfN5vPpGOmDkei2RlYrb3RAYNintUbixMlIr3jV6LGMlNL31BIEUv6/F0atMfhlv5wNODF+kH4wc7CiZY5KTcYbqWgQ0rMDoLeq+fiqljfj6aK8EX0m2wCZxmj3hMWRgEOVwMcEX7vlycuKI9wCse0h8EsUyfQq7h/r8P02AbbO6lzl4MaZgOEzPeWBLBGSQSTR4nbZfWgX+5Ny1m4DiCEMk4LrHELXR9CacnHxE1NDLV2YMD5kguO2lEvugbFlXs8nQpgh8nrf5A39mMXbhzoDVRoB3b2PqzbgcihDwvpTEWELLhdw4A+b12s2hMuBqd1FWxkwQGrNc=
